//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbStoreWebEntities : DbContext
    {
        public dbStoreWebEntities()
            : base("name=dbStoreWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbBrand> tbBrands { get; set; }
        public virtual DbSet<tbCategory> tbCategories { get; set; }
        public virtual DbSet<tbCity> tbCities { get; set; }
        public virtual DbSet<tbCountry> tbCountries { get; set; }
        public virtual DbSet<tbCustomer> tbCustomers { get; set; }
        public virtual DbSet<tbDocument> tbDocuments { get; set; }
        public virtual DbSet<tbEmployee> tbEmployees { get; set; }
        public virtual DbSet<tbGender> tbGenders { get; set; }
        public virtual DbSet<tbOrder> tbOrders { get; set; }
        public virtual DbSet<tbPosition> tbPositions { get; set; }
        public virtual DbSet<tbProductOrder> tbProductOrders { get; set; }
        public virtual DbSet<tbProduct> tbProducts { get; set; }
        public virtual DbSet<tbProvider> tbProviders { get; set; }
        public virtual DbSet<tbRegion> tbRegions { get; set; }
        public virtual DbSet<tbShippingCompany> tbShippingCompanies { get; set; }
        public virtual DbSet<tbStateOrder> tbStateOrders { get; set; }
        public virtual DbSet<tbSubCategory> tbSubCategories { get; set; }
        public virtual DbSet<tbSubCategoryProduct> tbSubCategoryProducts { get; set; }
    }
}
