//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEmployee()
        {
            this.tbOrders = new HashSet<tbOrder>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public int IdDocument { get; set; }
        public int IdGender { get; set; }
        public int IdCity { get; set; }
    
        public virtual tbCity tbCity { get; set; }
        public virtual tbDocument tbDocument { get; set; }
        public virtual tbGender tbGender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbOrder> tbOrders { get; set; }
    }
}
