//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbOrder()
        {
            this.tbProductOrders = new HashSet<tbProductOrder>();
        }
    
        public int Id { get; set; }
        public string RecipientAdress { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string PostalCode { get; set; }
        public string District { get; set; }
        public string SpecialInstruction { get; set; }
        public int IdStateOrder { get; set; }
        public int IdCustomer { get; set; }
        public int IdEmployee { get; set; }
        public int IdCity { get; set; }
        public int IdShippingCompany { get; set; }
    
        public virtual tbCity tbCity { get; set; }
        public virtual tbCustomer tbCustomer { get; set; }
        public virtual tbEmployee tbEmployee { get; set; }
        public virtual tbShippingCompany tbShippingCompany { get; set; }
        public virtual tbStateOrder tbStateOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProductOrder> tbProductOrders { get; set; }
    }
}
