//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbProduct()
        {
            this.tbProductOrders = new HashSet<tbProductOrder>();
            this.tbSubCategoryProducts = new HashSet<tbSubCategoryProduct>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public byte State { get; set; }
        public int Stock { get; set; }
        public int Discount { get; set; }
        public decimal InternalPrice { get; set; }
        public decimal PublicPrice { get; set; }
        public string Description { get; set; }
        public string ProductDetail { get; set; }
        public int IdBrand { get; set; }
        public int IdProvider { get; set; }
    
        public virtual tbBrand tbBrand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProductOrder> tbProductOrders { get; set; }
        public virtual tbProvider tbProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSubCategoryProduct> tbSubCategoryProducts { get; set; }
    }
}
