//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSubCategoryProduct
    {
        public int Id { get; set; }
        public int IdProduct { get; set; }
        public int IdSubCategory { get; set; }
    
        public virtual tbProduct tbProduct { get; set; }
        public virtual tbSubCategory tbSubCategory { get; set; }
    }
}
