//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSubCategory()
        {
            this.tbSubCategoryProducts = new HashSet<tbSubCategoryProduct>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public byte State { get; set; }
        public string Description { get; set; }
        public int IdCategory { get; set; }
    
        public virtual tbCategory tbCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSubCategoryProduct> tbSubCategoryProducts { get; set; }
    }
}
